name:                borg-runner
version:             0.1.0.0
github:              "denibertovic/borg-runner"
license:             GPL
author:              "Deni Bertovic"
maintainer:          "deni@denibertovic.com"
copyright:           "2018 Deni Bertovic"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/borg-runner#readme>

ghc-options:
# - -Werror
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude


dependencies:
- base >= 4.7 && < 5
- yaml
- optparse-applicative
- text
- aeson
- directory
- unix
- time
- rio

library:
  source-dirs: src

executables:
  borg-runner:
    main:                Main.hs
    source-dirs:         app
    other-modules: Paths_borg_runner
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - borg-runner

tests:
  borg-runner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - borg-runner
